# Generated by Django 4.2.15 on 2024-10-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('strategy_name', models.CharField(max_length=100)),
                ('current_position', models.FloatField()),
                ('profit_loss', models.FloatField()),
            ],
        ),
    ]
