# Generated by Django 4.2.15 on 2024-10-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyinfo',
            name='avg_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='strategyinfo',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategyinfo',
            name='leverage',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='strategyinfo',
            name='mark_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='strategyinfo',
            name='position_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='strategyinfo',
            name='side',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='strategyinfo',
            name='transaction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategyinfo',
            name='current_position',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='strategyinfo',
            name='profit_loss',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='strategyinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
